<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-O6A5C2O" failures="4" tests="28" name="com.tetherfi.test.ivr.BranchManagementCreateTest" time="953.774" errors="0" timestamp="2019-10-24T11:14:35 IST" skipped="6">
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAddCancelButton" time="46.079"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAddRecordwithoutMainLines" time="43.806"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAddRecordWithoutSubLines" time="44.474"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAddRecordWithoutLocation" time="54.102"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAddRecordWithoutBranchType" time="43.794"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAddRecordWithoutBranchName" time="47.949"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAddRecordWithoutAddress" time="38.042"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAddRecordWithoutLineOrder" time="50.495"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAddRecordWithoutStatus" time="46.533"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAddRecordWithoutLanguage" time="44.017"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="AddRevertRecord" time="48.207"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyRevertForAddNewRecord" time="34.704">
    <failure message="approal status details failed did not expect to find [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: approal status details failed did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.tetherfi.test.ivr.BranchManagementCreateTest.VerifyRevertForAddNewRecord(BranchManagementCreateTest.java:186)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyRevertForAddNewRecord -->
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyApprovedDataSectionWithoutApproval" time="26.479">
    <skipped/>
  </testcase> <!-- VerifyApprovedDataSectionWithoutApproval -->
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAuditTrailReportForRevert" time="24.581">
    <skipped/>
  </testcase> <!-- VerifyAuditTrailReportForRevert -->
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="AddRejectRecord" time="45.531"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifySendForApprovalForAddNewRecord" time="35.423"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="RejectforAddNewBranchManagementRecord" time="34.119">
    <failure message="did not expect to find [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.tetherfi.test.ivr.BranchManagementCreateTest.RejectforAddNewBranchManagementRecord(BranchManagementCreateTest.java:236)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- RejectforAddNewBranchManagementRecord -->
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAuditTrailReportForReject" time="27.195">
    <skipped/>
  </testcase> <!-- VerifyAuditTrailReportForReject -->
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyRecordAfterRejection" time="26.538">
    <skipped/>
  </testcase> <!-- VerifyRecordAfterRejection -->
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="AddNewBranchManagementRecord" time="43.656"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAuditTrailReportForCreate" time="49.389"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAuditTrailDataForAddNewBranchManagementRecord" time="31.841"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifySendForApprovalForAddNewBranchManagementRecord" time="9.864"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAuditTrailReportForSendForApproval" time="20.226"/>
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="ApproveforAddNewBranchManagementRecord" time="16.585">
    <failure message="did not expect to find [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at org.testng.Assert.assertTrue(Assert.java:53)
at com.tetherfi.test.ivr.BranchManagementCreateTest.ApproveforAddNewBranchManagementRecord(BranchManagementCreateTest.java:327)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- ApproveforAddNewBranchManagementRecord -->
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyAuditTrailReportForApprove" time="0.001">
    <skipped/>
  </testcase> <!-- VerifyAuditTrailReportForApprove -->
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="VerifyRecordApprovedDataSectionafterApproval" time="0.000">
    <skipped/>
  </testcase> <!-- VerifyRecordApprovedDataSectionafterApproval -->
  <testcase classname="com.tetherfi.test.ivr.BranchManagementCreateTest" name="AddDuplicateRecord" time="20.144">
    <failure message="Duplicate assetion failed did not expect to find [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Duplicate assetion failed did not expect to find [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertFalse(Assert.java:65)
at com.tetherfi.test.ivr.BranchManagementCreateTest.AddDuplicateRecord(BranchManagementCreateTest.java:361)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- AddDuplicateRecord -->
</testsuite> <!-- com.tetherfi.test.ivr.BranchManagementCreateTest -->
